# Defines application language and version
language: php
php:
  - '7.0'

# Installs required dependencies
install:
  - composer install
  - composer dump

# Defines build script
script:
  - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

# Sends data to coveralls
after_success:
  - travis_retry php vendor/bin/coveralls -v
