# Defines application language and version
language: php
php:
  - '7.0'
  - '7.1'

# Installs required dependencies
install:
  - composer install
  - composer dump

# Defines build script
script:
  - vendor/bin/phpunit tests

# Sends data to coveralls
after_success:
  - travis_retry php vendor/bin/coveralls -v
